### ISSUE TITLE
Is winax entirely blocking and synchronous?

### ISSUE THREAD

**Issue by vicboyv** [durs/node-activex#31]
I'm aware that @durs is working on an asynchronous feature, but is that the reason why I can't control several COM objects in parallel? 

I was almost done with my MVP when I noticed that running several instances of my application worked sequentially rather than simultaneously (one-by-one); even when wrapping it in promises or callbacks.

The only solution I found was to run several processes. Why did that work exactly?

I'm currently designing a multi-process approach as a workaround, but I'd like confirmation that this is really the case and not some design flaw on my async or VM implementation.

@durs thank you for creating this awesome tool, I hope you could help me out in one way or another.

If you want to know the application in question, I'll gladly share it privately. Not really sure if I could freely disclose it.

Thanks again!

**Comment by TechQuery** [comment]
I think so, you can refer to my package --- https://github.com/TechQuery/Puppeteer-IE#known-issue

**Comment by TechQuery** [comment]
COM+ is inherently synchronous, method invoking of COM+ objects will block the main thread of Node.JS...

**Comment by durs** [comment]
It all depends on the architecture of COM objects, but most of them work in blocking mode. 
Therefore, invoke COM method, such as 
``
var rs = adocon.Execute("select * from test"); 
``
blocks the main thread of the NodeJS as well as in the CScript. For NodeJS this is a bad style. 
I tried to create an asynchronous feature when the COM object is running in a parallel thread, so that the main thread of the NodeJS is not blocked, and all calls must return a Promise object.
``
adocon.Execute("select * from test").then(rs => {
}); 
``
But there is not enough time to solve this problem
@vicboyv In your case, the only solution is to run several processes.

**Comment by vicboyv** [comment]
@TechQuery @durs Thanks guys, I'll just do multi-processing then!

Closed.
