### ISSUE TITLE
Issue with VARIANT_BOOL

### ISSUE THREAD

**Issue by erikleo** [durs/node-activex#41]
I am using winax to access a VBA macro in excel after calling 

```
oXL = new winax.Object('Excel.Application');
oXL.Run('MyWorkbook.xla!MyMacro', parameter);
```

The problem i see is that inside the VBA macro, a C++ dll is called that returns a variant bool.  In c++ the true value for this is represented a short with value -1

the MyMacro function returns a vba type of boolen however the result comes from the C++ dll and it comes back as false in javascript even though the vba function returns true.

I have a workaround that instead of returning the value of the c++ call directly, check if it is true then then return true.  For example:

```
Public Function MyMacro() as Boolean
        MyMacro=cppObject.Result()
End Function
```
becomes
```
Public Function MyMacro() as Boolean
    If cppObject.Result() then
        MyMacro=True
    Else
        MyMarco=False
    End If
End Function
```
However this may be coming up a lot.  Is there any way to handle this case within winax itself?

**Comment by durs** [comment]
There should be no problems, because
result VARIANT with type VT_BOOL converted as (see utils.cpp)
Local<Value> Variant2Value(Isolate *isolate, const VARIANT &v, bool
allow_disp) {
....
case VT_BOOL:
return Boolean::New(isolate, (by_ref ? *v.pboolVal : v.boolVal) ==
VARIANT_TRUE);
...
}
where
#define VARIANT_TRUE ((VARIANT_BOOL)-1)
#define VARIANT_FALSE ((VARIANT_BOOL)0)



чт, 13 дек. 2018 г. в 00:41, Erik <notifications@github.com>:

**Comment by erikleo** [comment]
Thanks for the reply Yuri, turns out the type issue was from the underlying c++ dll we were referencing.
